FROM registry.fedoraproject.org/f33/python3
# ARGS for dockerfile

ARG SH_GIT_URL
ARG SH_GIT_BRANCH

#
#
# Add application sources to a directory that the assemble script expects them
# and set permissions so that the container runs without root access
USER 0
#COPY . /tmp/src
RUN git clone ${SH_GIT_URL} /tmp/src -b ${SH_GIT_BRANCH}


RUN /usr/bin/fix-permissions /tmp/src
USER 1001

# Install the dependencies
RUN python3.9 -m pip install --upgrade pip
RUN /usr/libexec/s2i/assemble
EXPOSE 8080
# EXPOSE 5000
# Set the default command for the resulting image
CMD /usr/libexec/s2i/run
